### ISSUE TITLE
MINOR: master variable

### ISSUE THREAD

**Issue by Kreyren** [Rogentos/argent-ws#1]
`ebuild <name>.ebuild digest` outputs:

```Appending /usr/local/portage to PORTDIR_OVERLAY...
!!! Repository 'x-portage' is missing masters attribute in '/usr/local/portage/metadata/layout.conf'
!!! Set 'masters = argent-ws' in this file for future compatibility
```

Since `/usr/local/portage` is present by default then variable `masters = argent-ws` should be added to `/usr/local/portage/metadata/layout.conf` to prevent this error.

NOTE: i have no idea why is it required.

**Comment by StefanCristian** [comment]
It's happening only on binmode if you try to compile own stuff, which is not possible in those conditions
Closing

**Comment by Kreyren** [comment]
is still annoying on something that is argent's feature tho..

**Comment by StefanCristian** [comment]
Agreed @ annoyance, but you're not supposed to use ebuild if you don't have /usr/portage populated

You could've just _cd /usr/portage_ and _git pull_ before using ebuild 👍

**Comment by Kreyren** [comment]
meh, i still hate it but fair enough
